# Site settings
permissions:
  id-token: write
  contents: read

title: Ananya Kotia
description: ''
url: 'https://ananyakotia.com'
baseurl: ""
google_analytics: '89138162'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ananya Kotia'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

timezone: EST5EDT

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - AGENTS.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - website.sublime-project
  - website.sublime-workspace
