# Site settings
title: Ananya Kotia
description: Ph.D. candidate, Department of Economics, London School of Economics \n \n a.kotia1@lse.ac.uk
url: 'https://ananyakotia.com'
baseurl: ""
google_analytics: '89138162'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ananya Kotia'
  email: a.kotia1@lse.ac.uk

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

timezone: EST5EDT

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

plugins: ['jekyll-paginate', 'jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

